// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEvent(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['calenderwidget']['CalenderUser']['CreateEvent'](arg1, arg2, arg3, arg4, arg5);
}
