// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNote(arg1, arg2) {
  return window['go']['notewidget']['NoteUser']['CreateNote'](arg1, arg2);
}

export function GetNotes() {
  return window['go']['notewidget']['NoteUser']['GetNotes']();
}
