// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {notewidget} from '../models';

export function CreateNote(arg1:string,arg2:string):Promise<notewidget.NoteObject>;

export function GetNotes():Promise<Array<notewidget.NoteObject>>;
